framework:
  router:
    # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
    # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
    default_uri: "https://tmdb.ludovicdev.com/"

when@prod:
  framework:
    router:
      strict_requirements: null
