twig:
  file_name_pattern: "*.twig"
  default_path: "%kernel.project_dir%/templates"
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  exception_controller: null
  form_themes: ["bootstrap_5_layout.html.twig"]
  globals:
    site_name: "TMDB App"
  paths:
    "%kernel.project_dir%/public/css": css
    "%kernel.project_dir%/public/images": images
  date:
    format: "d/m/Y"
    interval_format: "%%d jours"
    timezone: Europe/Paris

when@test:
  twig:
    strict_variables: true
